version: "3.8"

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sq1compli
    volumes:
      - ./docker/mysqldata:/var/lib/mysql
      - ./docker/mysql/createDevDB.sql:/docker-entrypoint-initdb.d/init1.sql

  php:
    image: laravel_docker    # Explicitly set the image name here
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        buildno: 1.0
    ports:
      - 8082:80
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - "db"

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8083:8080
    depends_on:
      - "db"
